package com.zhidi.server.notification;

public enum BusinessEventType {
	DAILY_REPORT_SUBMITTED,
	INSPECTION_REQUESTED,
	INSPECTION_RECTIFICATION_REQUIRED,
	INSPECTION_PASSED,
	AFTER_SALE_CREATED,
	AFTER_SALE_PARTICIPANT_MESSAGE,
	AFTER_SALE_PLATFORM_ACCEPTED,
	AFTER_SALE_PLATFORM_REPLIED,
	AFTER_SALE_RESOLVED,
	AFTER_SALE_CLOSED
}
